version: "3.9"  # optional since v1.27.0
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    #команда для исполнения
    command: gunicorn -b 0.0.0.0:5000 hello:app --reload
    #открыть как http://127.0.0.1:5000/
    #системная переменная
    environment:
      - FLASK_APP=hello.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=True
    volumes:
      - ./:/root
